modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/mickelus/tetra/issues/new?template=bug_report.md"
license="MIT"

[[mods]]
modId="tetra"
version="${file.jarVersion}"
displayName="Tetra"
authors="Mickelus"
description="Tetra revolves around modular items and attempts to blend it together with other concepts such as adventure and technology."
credits="red1854th: korean localization, Jeffku0107: chinese localization, Arvid6: spanish localization"

[[dependencies.tetra]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="mgui"
    mandatory=true
    versionRange="[3.2,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.2-4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tetra]]
    modId="botania"
    mandatory=false
    versionRange="[1.16,)"
    ordering="AFTER"
    side="BOTH"
